; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
; platform = espressif32
;platform = espressif32@6.12.0
;platform = https://github.com/platformio/platform-espressif32.git#develop
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip ;Necessário para compilar com a versão 3.0.2 do framework Arduino-ESP32 (Suporte para W5500 nativo)
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Ativa o USB nativo para o Serial do Arduino
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=4 ; (0: None, 1: Error, 2: Warn, 3: Info, 4: Debug, 5: Verbose)
;Habilita o suporte ao W5500 nativo (Necessário para a placa da Ancora)
;    -D USE_NATIVE_ETHERNET=1

;Habilita todos os logs:s
    

; Altera o tamanho do flash para 4MB e define a partição padrão (Necessário na PCB da Ancora)
board_upload.flash_size = 4MB
board_build.partitions = partitions.csv
; board_build.partitions = default.csv

;platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
